### ISSUE TITLE
Use k8s secrets in env vars

### ISSUE THREAD

**Issue by ghost** [keptn-sandbox/keptn-osticket-service#1]
Currently, sensitive data is stored in plain text in the service yaml definition: https://github.com/Dynatrace-Adam-Gardner/keptn-osticket-service/blob/ea897479a8176814dd4292dfa07b146558baca97/osticket-service.yaml#L22

This enhancement covers the work to encrypt the sensitive data using k8s secrets.

https://medium.com/faun/using-kubernetes-secrets-as-environment-variables-5ea3ef7581ef

**Comment by jetzlstorfer** [comment]
An example from the keptn-sandbox org: https://github.com/keptn-sandbox/generic-executor-service/blob/master/deploy/service.yaml#L38

**Comment by ghost** [comment]
Solved in PR #2
